### ISSUE TITLE
9. My Profile

### ISSUE THREAD

**Issue by brickcube** [brickcube/KBKSearch#26]
A logged-in user should able to view his profile and allow to update modifiable fields in same. It should have different sections and allow to modify each section independently.
- [ ] a. Switch Business - A vendor can hold multiple businesses with same login. If a logged-in user want to switch to his other business, he should able to do without re-login.
- [ ] b. Change Password - Logged-in users should be able to change their existing password.
- [ ] c. Change Avatar - Logged in users should be able to change their profile picture or avatar.
- [ ] d. Update Profile - Logged in users should be able to modify updatable details i.e. email/mobile numbers etc.
- [ ] e. Renew subscription - Authorised users should be able to renew subscription online.
- [ ] f. Tax Management - Authorised users should be able to view report of tax paid through the system.

**Comment by ravi-brickcube** [comment]
This issue was moved to brickcube/vendorCube#48
