### ISSUE TITLE
10. Offer & Promotion Management

### ISSUE THREAD

**Issue by brickcube** [brickcube/KBKSearch#30]
- [ ] a. Authorised users should be able create/update/delete Promotions eg. “Celebrate Republic Day in Vijay Sales”.
- [ ] b. Authorised users should be able create/update/delete various offers under a Promotion eg. “Buy One Microwave Oven and get cooktop free” under “Celebrate Republic Day in Vijay Sales”.
- [ ] c. Authorised users should be able create/update/delete discount under a Promotion eg. “50% off on Washing Machine” under “Celebrate Republic Day in Vijay Sales”.
- [ ] d. Authorised users should be able create/update/delete discount coupons.
- [ ] e. Authorised users should be able to buy additional promotion credits by making necessary payment online.
- [ ] f. Authorised users should be able to see their promotions usage report along with remaining promotions.

**Comment by ravi-brickcube** [comment]
This issue was moved to brickcube/vendorCube#51
