### ISSUE TITLE
6. Order Management.

### ISSUE THREAD

**Issue by brickcube** [brickcube/KBKSearch#33]
- [ ] a. System should provide notifications of orders to all authorised users with visual and audio alerts. If action is not taken by any of the users on the order notifications, appropriate alerts should be displayed in the screen.
- [ ] b. Order alert screen should autoclose and auto-cancel orders if no action is taken within a defined period of time.
- [ ] c. Both web based client and mobile based client should maintain connection with the server so that server can push notifications and other messages to the client device.
- [ ] d. Customers and/or system should be able to cancel orders and if an order is canceled by either of the actors, the order should disappear from Vendor’s UI with appropriate status. History of canceled orders should be available to users as a report.
- [ ] e. Authorised users should be able accept Order placed by Customers.
- [ ] f. Authorised users should be able reject order placed by customers with a reason.
- [ ] g. Authorised users should be able to process accepted order.
- [ ] h. Authorised users should be able to change the state of order processed eg. in Transit, delivered etc.
- [ ] i. Authorised users should be able to view list of orders and should be able to filter it with their status, area of customer or more criterias.
- [ ] j. Authorised users should be able to get Report of all orders depending on various criterias.
- [ ] k. Authorised users should be able to initiate return order process which are requested by customers.
- [ ] l. Authorised users should be able to print invoice of his order. Invoice should contain details of order including product details, payment status and payment mode. Format of invoice will be provided later.
- [ ] m. Authorised user should be able to print Return Product Order Acknowledgement.
- [ ] n. Authorised users should be able to create a new order in system. This happens when customer is a walk-in customer and vendor wants to track the order using the system. Customer id in this case is not mandatory, but order will be tracked based on mobile number of the customer.
- [ ] o. Vendors should be able to raise disputes related to orders or return orders.

**Comment by ravi-brickcube** [comment]
This issue was moved to brickcube/vendorCube#31
