### ISSUE TITLE
4. Product & Service Management

### ISSUE THREAD

**Issue by brickcube** [brickcube/KBKSearch#34]
- [ ] a. Authorized user should be able to create, modify, remove, view their products and services.
- [ ] b. Product Properties should be fetched from the Product Type, which the product belongs to. Similarly Service Properties should be fetched from Service Type which the service belongs to.
- [ ] c. Authorized users should be able to add more properties than those available in product type or service type for the product or service which they are creating.
- [ ] d. Authorized user should be able to associate globally available general products and globally available general services to his business rather than creating new products and services.
- [ ] e. Authorized user should be able add, edit, view and delete assets i.e. images, documents, videos to his products and/or services.
- [ ] f. Authorized users should be able to change the selling price of their products or services.
- [ ] g. Authorized user should be able to change availability of any products or services.
- [ ] h. Authorized user should be able to change enable/disable Home delivery options of products.
- [ ] i. Authorized user should be able to change the value of overridable fields in his product or services.
- [ ] j. Authorized users should be able to see all product or services’ list associated with his business.
- [ ] k. Authorized user should be able to associate/create questionnaire for their services.

**Comment by ravi-brickcube** [comment]
This issue was moved to brickcube/vendorCube#7

**Comment by ravi-brickcube** [comment]
This issue was moved to brickcube/vendorCube#9
